services:
  db:
    container_name: DB_CONTAINER
    image: mariadb:latest
    volumes:
      - DB_VOLUME:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_passwd
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: your_password
    networks:
      - network

  wordpress:
    depends_on:
      - db
    container_name: APP_CONTAINER
    image: wordpress:fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - APP_VOLUME:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - network

  nginx:
    container_name: NGINX_CONTAINER
    image: nginx:latest
    restart: always
    ports:
      - "PORT:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - APP_VOLUME:/var/www/html
    depends_on:
      - wordpress
    networks:
      - network

volumes:
  DB_VOLUME:
  APP_VOLUME:

networks:
  network:
